var grid = $('.grid-section');

grid.click(function(){
    var count = $('div.grid-display').length;
    var height = $('.grid-inner').width();
    if (count === 1) {
        $('.brand-logos').remove();
    }
    else {
        if ($(this).attr('id') === 'identityId') {
            $(this).after('<section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/YG_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/GE_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DT_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/Alt_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/SL_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DR_Logo-2.jpg"></section>');
        } 
        else if ($(this).attr('id') === 'mobileId') {
            $(this).before('<section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section>');
            $(this).after('<section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/GE_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DT_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/Alt_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/SL_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DR_Logo-2.jpg"></section>');
        }
        else if ($(this).attr('id') === 'webId') {
            $(this).before('<section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section>');
            $(this).after('<section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/GE_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DT_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/Alt_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/SL_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DR_Logo-2.jpg"></section>');
        }
        else if ($(this).attr('id') === 'brandId') {
            $(this).after('<section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/GE_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DT_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/Alt_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/SL_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DR_Logo-2.jpg"></section>');
        }
        else if ($(this).attr('id') === 'spaceId') {
            $(this).before('<section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section>');
            $(this).after('<section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/GE_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DT_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/Alt_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/SL_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DR_Logo-2.jpg"></section>');
        }
        else if ($(this).attr('id') === 'productId') {
            $(this).before('<section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section>');
            $(this).after('<section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/GE_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DT_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/Alt_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/SL_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DR_Logo-2.jpg"></section>');
        }
        else if ($(this).attr('id') === 'movieId') {
            $(this).after('<section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/GE_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DT_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/Alt_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/SL_Logo-2.jpg"></section><section class="brand-logos left-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DR_Logo-2.jpg"></section>');
        }
        else if ($(this).attr('id') === 'eventId') {
            $(this).before('<section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section>');
            $(this).after('<section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/GE_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DT_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/Alt_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/SL_Logo-2.jpg"></section><section class="brand-logos center-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DR_Logo-2.jpg"></section>');
        }
        else if ($(this).attr('id') === 'contentId') {
            $(this).before('<section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section>');
            $(this).after('<section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/CM_Logo-1.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/GE_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DT_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/Alt_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/SL_Logo-2.jpg"></section><section class="brand-logos right-brand animate__animated animate__fadeIn"><img class="" src="images/product_logos/DR_Logo-2.jpg"></section>');
        }
    }
    $('.brand-logos').css('height',height);
});